### ISSUE TITLE
what is ROOT_PATH ？

### ISSUE THREAD

**Issue by Zongyang-Li** [endrikacupaj/LASAGNE#1]
Hello, thanks for your sharing and contributions.
When I tried to reproduce the code, I encountered an error which said that “ROOT_PATH is not defined” in prepare_data.py.  I tried to specify it as the dataset address, but the error did not change.
What does ROOT_PATH.parent mean ？And how to specify the value of ROOT_PATH ?

**Comment by ameyrathi** [comment]
Hey,
i am trying to reproduce this code as well.
ROOT_PATH is present in constants file in the root directory
You will need to add the following code in the prepare_data.py
```
import sys
sys.path.append("/path/to/dir/LASAGNE")
from constants import *
```
I am not sure why ROOT_PATH.parent is used everywhere so I have changed the assignment of ROOT_PATH as well in constants.py
`
ROOT_PATH = Path(__file__)
`
