### ISSUE TITLE
Why use next context when question type is "Clarification" ?

### ISSUE THREAD

**Issue by runzewang** [endrikacupaj/LASAGNE#7]
Hi, 
  When question type is  "Clarification", you concat the next context tokens after current context in dataset._prepare_data and dataset.get_inference_data function, and treat the next system golden action as the currenct golden action, why are you doing this  ? I think it will reduce the question number with "Clarification" type, and lead to a unfair compare with others.

Waiting for your responds. 
Best,

**Comment by joanPlepi** [comment]
Hi, 

I think this is mainly a small confusion from the way the dataset is constructed and how are the question types structured. In the case when in the current turn is question_type == 'Clarification', there is no such answer that it can be retrieved from the knowledge because the context is unclear, and the system just responds with a generated template in the format of "Did you mean X?". For this scenario, what we are able to generate a response from the knowledge graph, is the follow-up turn, where the user clarifies the context "No, I meant Y.", and the system is able to search for an answer in the knowledge graph. 
This is consistent with the way how the previous work have evaluated this kind of question type.

**Comment by runzewang** [comment]
> Hi,
> 
> I think this is mainly a small confusion from the way the dataset is constructed and how are the question types structured. In the case when in the current turn is question_type == 'Clarification', there is no such answer that it can be retrieved from the knowledge because the context is unclear, and the system just responds with a generated template in the format of "Did you mean X?". For this scenario, what we are able to generate a response from the knowledge graph, is the follow-up turn, where the user clarifies the context "No, I meant Y.", and the system is able to search for an answer in the knowledge graph. This is consistent with the way how the previous work have evaluated this kind of question type.

Another question is , you reset the question type as a list in dataset.get_inference_data function when question_type == 'Clarification', but when executing the actions in action_execute.run, the samples that "d['question_type'] != args.question_type" are ignored. All the questions with question_type == 'Clarification' will be ignored? right?

BTW, the author of CSQA has offered a metric for questions which need clarificatio. See section "Result" in "", and I cite it below.
"Finally for questions which need clarification, the system has to generate a natural language response which is usually a sequence of KG-entities and non-KG words, hence for that we separately report both Precision/Recall over the predicted KG-entities and BLEU for the overall utterance similarity."

**Comment by joanPlepi** [comment]
As I explained above, the question type clarification, have the answer in the next utterance, after the context is clarified. Hence, the current turn is skipped. 

Yes, the CSQA authors have offered a metric for the turn which needs a clarification, but as I was mentioning above, if we were to focus on these, it would be another task. As you have pointed out, this would be answer generation, that needs to be evaluated with BLEU score. Answer generation is out of the scope of this work.

**Comment by runzewang** [comment]
Thank you for your responds.
If we skipped current turn in action_execute.run file, how we get the Clarification result?
The code "https://github.com/endrikacupaj/LASAGNE/blob/6321ab5161999905b357bd9b67906dcac04b8644/dataset.py#L325"
and 
"https://github.com/endrikacupaj/LASAGNE/blob/6321ab5161999905b357bd9b67906dcac04b8644/action_executor/run.py#L50"
will cause that all the questions whose question_type is a list will be skipped.

**Comment by joanPlepi** [comment]
> Thank you for your responds. If we skipped current turn in action_execute.run file, how we get the Clarification result? The code "
> 
> https://github.com/endrikacupaj/LASAGNE/blob/6321ab5161999905b357bd9b67906dcac04b8644/dataset.py#L325
> 
> "
> and
> "
> https://github.com/endrikacupaj/LASAGNE/blob/6321ab5161999905b357bd9b67906dcac04b8644/action_executor/run.py#L50
> 
> "
> will cause that all the questions whose question_type is a list will be skipped.

The clarification question type, it is different from the other question types, it contains two turns of utterances. So to speak, the performance of clarification question types, is dependent from the follow-up question, the one that clarifies the context. This is aligned on how the previous works have also evaluated this question type (see [Tao Shen et al.](https://aclanthology.org/D19-1248.pdf) footnote 7 might add up to the clarification).

**Comment by runzewang** [comment]
Now, I understand it. Thank you for your patience.

**Comment by joanPlepi** [comment]
> Now, I understand it. Thank you for you patience.

Glad I was able to help! 

Thank you for your interest in our work and have a nice day :)
